
ALTER TABLE public.shopee_orders
ADD COLUMN IF NOT EXISTS tracking_number TEXT,
ADD COLUMN IF NOT EXISTS shipping_provider TEXT,
ADD COLUMN IF NOT EXISTS buyer_username TEXT,
ADD COLUMN IF NOT EXISTS shopee_voucher DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS voucher_code TEXT,
ADD COLUMN IF NOT EXISTS payment_method TEXT,
ADD COLUMN IF NOT EXISTS date_paid TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS date_shipped TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS date_completed TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS date_released TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS commission_fee DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS service_fee DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS transaction_fee DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS support_program_fee DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_shipping_fee DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS shipping_fee_paid_by_buyer DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS shipping_fee_rebate DECIMAL DEFAULT 0;

NOTIFY pgrst, 'reload schema';
